### PR TITLE
added frk

### PR DESCRIPTION
**Pull request by chrisfranko**
add franko

### CODE REVIEW

**Comment by allienworks** [comment]
Thanks for input! FRK was already suggested in reddit, I will add it in next update. Cheers!

**Comment by chrisfranko** [comment]
thanks alot!

**Comment by allienworks** [comment]
Hey @chrisfranko, I wanted to ask -- your added FRK is a bit different from the official logo at FRK's website.. I've made [one that resembles the official logo](http://i.imgur.com/of0zd1B.png). Are you by any chance FRK's dev? Which one would you prefer?

**Comment by chrisfranko** [comment]
Ah Yes im the developer and I like that one too, could be a good
alternative, the stars are pretty important to the logo though. :)Each
point of the star represents one of the collective initiatives.

Nutrition, Housing, Healthcare, Education and protection from aggression.

**Comment by allienworks** [comment]
Ah, all right. Well I've _just_ released another update (with my version), so I could edit it later.. I try to keep the icons simple, so they can be used in even really small sizes (which means not that much details). Hmm, dilemma.. Let me know.

**Comment by chrisfranko** [comment]
should probably be ok

**Pull request closed without merging**
