### PR TITLE
Added coins

### PR DESCRIPTION
**Pull request by quoid**
I added the following coins:

* ARK (ARK) - issue #85 
* Byteball (GBYTE) - issue #86 
* Bytom (BTM)
* Cardano (ADA)
* QTUM (QTUM) - issue #82 
* SALT (SALT) 
* ZCoin (XZC) - issue #79 

and updated the demo page

### CODE REVIEW

**Comment by allienworks** [comment]
Very nice! This is amazing contribution, thanks @quoid!

It's quite funny, I already had some of the icons drawn myself, but the SVGs (and therefore the webfonts as well) got somehow damaged.. That's what you get when you want to experiment with different vector software!

**Can I just ask you for a few changes?**

- `XZC-alt` seems to have some trouble in webfont as well (it's just a black circle without logo)
- `SALT` (+ `-alt`): could you use just the triangle symbol?
- `GBYTE` is just a black circle as well, but I guess that was intended, right? (I wasn't really sure how to draw it myself :)

Everything else is spot on! Really good work. There were already few people that contributed icons, but you managed to keep the style of the iconpack the same. Thanks much!

**Comment by quoid** [comment]
Thanks @allienworks, you've done an amazing job so far and just want to lend a hand where I can!

> SALT (+ -alt): could you use just the triangle symbol?

For sure; that was the original one I made, but I thought it looked a little bare so wasn't sure. I'll make this change.

> GBYTE is just a black circle as well, but I guess that was intended, right? (I wasn't really sure how to draw it myself :)

Yeah I was surprised how basic their logo was. I saw the request in issue #86 and took a look at [the website](https://byteball.org) and surprising enough it's *just a circle*, haha.

If you have any ideas how to spice it up let me know!

> XZC-alt seems to have some trouble in webfont as well (it's just a black circle without logo)

I actually created a few other icons, but I was having so much difficulty with their webfont versions, that I said I would go back to them at a later date. I can't quite figure out why their `SVG` and `font` appearances are so different.

For `XZC-alt`, however, I didn't experience any issue with it displaying in the webfont on the `demo.html` page. I now just checked it in RoboFont and see it looks just like a blank circle, hrmm. I've attached screenshots of both the `demo.html` and robofont pages.

I will take a look further into this one.

> Everything else is spot on! Really good work. There were already few people that contributed icons, but you managed to keep the style of the iconpack the same.

Thanks! I created a template based off your other icons to try to keep everything uniform.

I'll post a comment when I've made those changes.

**Comment by quoid** [comment]
@allienworks fixed `XZC` and `SALT`

**Comment by pauliusuza** [comment]
is this good to merge?

**Comment by quoid** [comment]
@pauliusuza once the merge conflicts are resolved, it should be. I fixed all the concerns @allienworks had.

**Comment by allienworks** [comment]
@quoid aah, sorry, I didn't know you're finished :) The merge conflicts don't matter, as you've regenerated the webfonts with new icons, your version takes priority ofc. Let me merge this.

**Comment by allienworks** [comment]
Merged. Great work @quoid once again! You deserve a place in the readme next to 2.7 release :)

**Comment by quoid** [comment]
Thanks @allienworks - I have more contributions I can make, I'll send you an email off thread

**Pull request merged**
