### PR TITLE
remove unused class names and styles

### PR DESCRIPTION
**Pull request by yeahoffline**

### CODE REVIEW

**Comment by allienworks** [comment]
Thanks for help and clean-up! Just curious – have you removed the unused classes only in some coins or in all of them?

**Comment by yeahoffline** [comment]
did a search in files. hope i found all

**Comment by allienworks** [comment]
Great, thanks much for cooperation!

**Comment by yeahoffline** [comment]
glad to help, thanks for that amazing iconpack!

**Pull request merged**
