### PR TITLE
New LISK logo

### PR DESCRIPTION
**Pull request by artur-siwiak**
Lisk logo changed to new version

### CODE REVIEW

**Comment by AllienWorks** [comment]
@artur-siwiak thanks much for help and so sorry for late reply! Could I ask you for stretching the `LSK.svg` icon to the edges of the canvas (keep ratio ofc)? Then it would be perfect and ready to merge.

**Comment by artur-siwiak** [comment]
@AllienWorks : it will be enough if i'll update only svg or i should update also fonts?

**Comment by AllienWorks** [comment]
@artur-siwiak both please. The fonts are affected by this as well.

**Comment by AllienWorks** [comment]
Already added in another PR, thanks for the contribution!

**Pull request closed without merging**
