### PR TITLE
Added Viacoin Svg's

### PR DESCRIPTION
**Pull request by Onurrr**

### CODE REVIEW

**Comment by allienworks** [comment]
Hello @Onurrr, sorry but I can't merge this in its current form. This is my bad as I still haven't found the time to wirte proper contributing guidelines/howto.

Besides the new icons, you have to regenerate the webfont (`gulp webfont`) + if you're adding a new coin, it has to have defined main color in `cryptocoins-colors.css` and be added to `demo.html` file.

**Comment by Onurrr** [comment]
Paging @AllienWorks did all of the above stated, hope it's good now.

**Comment by Onurrr** [comment]
@AllienWorks changes have been made

**Comment by TheMike-V** [comment]
@AllienWorks Did you review the latest changes?

**Comment by AllienWorks** [comment]
Already added in another PR, still thanks much for the contribution!

**Pull request closed without merging**
