### PR TITLE
Added new coins

### PR DESCRIPTION
**Pull request by AdRock952**
Added new coins for:

- AirSwap (AST)
- Bluezelle (BLZ)
- FunFair (FUN)
- Metal (MTL)
- Mysterium (MYST)
- Numerai (NMR)
- RChain (RHOC)
- 0x (ZRX)

I've added alt versions where I can

### CODE REVIEW

**Comment by AllienWorks** [comment]
Thanks for the contribution, so sorry it took so long!

**Comment by AdRock952** [comment]
Hi Martin

I need to do some more and I've forgotten how to create the new icons.

I've used InkScape as before as I haven''t got Illustrator and I'm getting a problem wen previewing just shows all white.

I edited a previous SVG, updated the logo and saved it as a new file but they all come out white in the html preview. Previewing the actual SVG is fine.

Any ideas what's going wrong?

**Comment by Clystnet** [comment]
Hi Martin

I can get the export the SVG and if I view the SVG in a browser it's fine but when I add to the stylesheet and check with the other icons, it's all white.

I've got a funny feeling I'm missing something when I create the SVG.

**Comment by Clystnet** [comment]
Hi Martin

Don't worry...i realise what I did and should be able to create some more token icons.

Many thanks

Adam

**Pull request merged**
